name: PluginChallenges
version: '${project.version}'
main: net.dolphay.pluginchallenges.PluginChallenges
api-version: '1.19'

commands:
  challenges:
    description: To be implemented
    usage: To be implemented
    permission: pluginchallenges.reload
  greet:
    description: Greets a player, if no player is specified it greets the newest player.
    usage: /greet <player>
    permission: pluginchallenges.greet
  sword:
    description: Gives the player a really cool sword
    usage: /sword
    permission: pluginchallenges.sword
  warrior:
    description: Clears your inventory and gives you a worrier kit.
    usage: /warrior
    permission: pluginchallenges.warrior
  archer:
    description: Clears your inventory and gives you an archers kit.
    usage: /archer
    permission: pluginchallenges.archer
  mage:
    description: Clears your inventory and gives you an mages kit.
    usage: /mage
    permission: pluginchallenges.mage