name: PluginChallenges
version: '${project.version}'
main: net.dolphay.pluginchallenges.PluginChallenges
api-version: '1.19'

commands:
  challenges:
    description: Allows reloading of the different challenge configuration files
    usage: /challenges reload <Module>
    permission: pluginchallenges.reload
  greet:
    description: Greets a player, if no player is specified it greets the newest player.
    usage: /greet <player>
    permission: pluginchallenges.greet
